modLoader="javafml"

loaderVersion="[2,)"

license="MIT License"

[[mods]] #mandatory

modId="clickmachine"

version="9.0.0"

displayName="Click Machine"

authors="Shadows_of_Fire"

description='''A standalone auto-clicker mod, similar to the old Autonomous Actuator.'''

[[mixins]]
config="clickmachine.mixins.json"

[[dependencies.clickmachine]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.clickmachine]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.61,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.clickmachine]]
    modId="placebo"
    type="required"
    versionRange="[9.5.4,)"
    ordering="NONE"
    side="BOTH"
